safe: true
plugins:
  - jekyll-feed
theme: minima
title: FNAL EAF News
description: Subscribe to get news about the Fermilab EAF
baseurl: /newsfeed
exclude:
  - src
  - README.md
feed:
  posts_limit: 1
